 # Site Identity
title: "Cybersecurity Portfolio"
description: "Hands-on labs, investigations, and security analysis."

# GitHub Pages Jekyll Theme
remote_theme: just-the-docs/just-the-docs 

# Enabling custom CSS
just_the_docs:
  style_css:
    - assets/css/style.css

# Markdown & Formatting 
markdown: kramdown 
kramdown: 
  input: GFM

# GitHub Pages Settings
plugins: 
  - jekyll-include-cache

# Collections 
collections: 
  labs: 
    output: true 
    permalink: /labs/:name/
  writeups: 
    output: true 
    permalink: /writeups/:name/
  projects: 
    output: true 
    permalink: /projects/:name/
