 # Site Identity
title: "Cyberfolio"
description: "Hands-on labs, investigations, and security analysis."

# GitHub Pages Jekyll Theme
remote_theme: just-the-docs/just-the-docs 

# Dark mode 
color_scheme: dark

#Load the custom files
just_the_docs:
  custom_css:
    - custom

# Markdown & Formatting 
markdown: kramdown 
kramdown: 
  input: GFM

# GitHub Pages Settings
plugins: 
  - jekyll-include-cache

# Collections 
collections: 
  labs: 
    output: true 
    permalink: /labs/:name/
  writeups: 
    output: true 
    permalink: /writeups/:name/
  projects: 
    output: true 
    permalink: /projects/:name/
